#!/usr/bin/env python3
"""Controlled tmux GPU bridge for short ODCR validation probes.

This is a developer/Codex tool, not an ODCR user entrypoint.  It never creates
or manages GPU allocations.  It can only target a user-created tmux pane that is
already inside a live Slurm GPU step, and send-keys is limited to fixed
whitelist scripts generated by this file.
"""

from __future__ import annotations

import argparse
import dataclasses
import datetime as _dt
import json
import os
import re
import stat
import subprocess
import sys
import textwrap
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Sequence


REPO_ROOT = Path(__file__).resolve().parents[2]
AI_ANALYSIS = REPO_ROOT / "AI_analysis"
RAW_LOG_DIR = AI_ANALYSIS / "01_raw_logs"
SUMMARY_DIR = AI_ANALYSIS / "04_phase_summaries"
REPORT_DIR = AI_ANALYSIS / "05_final_reports"
RUNTIME_DIR = AI_ANALYSIS / "runtime"
STATE_FILE = RUNTIME_DIR / "gpu_pane.json"
D4C_PYTHON = Path("/public/home/zhangliml/miniconda3/envs/D4C/bin/python")
SAFE_TMPDIR = Path("/public/home/zhangliml/tmp/codex")
BRIDGE_STATUS_SCHEMA = "odcr_tmux_gpu_bridge_status/1.0"
GPU_PANE_SCHEMA = "odcr_gpu_pane/1.0"
TMUX_PANE_FORMAT = "\t".join(
    (
        "#{session_name}",
        "#{window_index}",
        "#{pane_index}",
        "#{pane_id}",
        "#{pane_pid}",
        "#{pane_current_command}",
        "#{pane_current_path}",
        "#{pane_active}",
        "#{pane_dead}",
        "#{pane_in_mode}",
    )
)


class BridgeError(RuntimeError):
    """Expected fail-fast bridge error with a stable stop reason."""

    def __init__(self, message: str, *, stop_reason: str = "target_invalid", details: Any = None) -> None:
        super().__init__(message)
        self.stop_reason = stop_reason
        self.details = details


@dataclass(frozen=True)
class CommandResult:
    args: tuple[str, ...]
    returncode: int
    stdout: str
    stderr: str


class SubprocessRunner:
    """Small wrapper so tests can mock every external command."""

    def run(self, args: Sequence[str], *, timeout: float | None = None) -> CommandResult:
        proc = subprocess.run(
            list(args),
            text=True,
            capture_output=True,
            check=False,
            timeout=timeout,
        )
        return CommandResult(tuple(str(part) for part in args), proc.returncode, proc.stdout, proc.stderr)


@dataclass(frozen=True)
class ModeSpec:
    name: str
    auto_timeout_s: int
    max_timeout_s: int
    startup_timeout_s: int
    first_result_timeout_s: int
    success_condition: str
    stop_reason_success: str
    send_allowed: bool


SEND_METHODS = (
    "pane-id-literal-enter",
    "target-name-literal-enter",
    "pane-id-literal-cm",
    "buffer-paste-enter",
)
DEFAULT_SEND_METHOD = "pane-id-literal-enter"
UNLOCK_OPERATIONS = ("copy-mode-cancel", "escape")


MODE_SPECS: dict[str, ModeSpec] = {
    "discover": ModeSpec(
        "discover",
        20,
        60,
        5,
        20,
        "exactly_one_valid_gpu_tmux_target_or_fail_fast",
        "target_validated",
        False,
    ),
    "validate-only": ModeSpec(
        "validate-only",
        20,
        60,
        5,
        20,
        "target_unique_and_slurm_gpu_metadata_valid",
        "target_validated",
        False,
    ),
    "unlock-pane": ModeSpec(
        "unlock-pane",
        20,
        60,
        5,
        20,
        "pane_mode_cancelled_and_target_revalidated",
        "pane_unlocked",
        False,
    ),
    "cuda-probe": ModeSpec(
        "cuda-probe",
        45,
        120,
        10,
        45,
        "torch_cuda_available_device_count_and_gpu_name",
        "first_cuda_probe_completed",
        True,
    ),
    "marker-probe": ModeSpec(
        "marker-probe",
        20,
        20,
        5,
        15,
        "begin_end_marker_and_send_ok_written_to_ai_analysis",
        "marker_probe_completed",
        True,
    ),
    "preprocess-dryrun": ModeSpec(
        "preprocess-dryrun",
        90,
        180,
        15,
        90,
        "preprocess_b_or_c_dry_run_exit_zero",
        "preprocess_dryrun_completed",
        True,
    ),
    "bge-smoke": ModeSpec(
        "bge-smoke",
        240,
        360,
        20,
        240,
        "local_bge_single_batch_encode_completed",
        "first_bge_encode_completed",
        True,
    ),
    "micro-benchmark": ModeSpec(
        "micro-benchmark",
        300,
        420,
        20,
        300,
        "one_warmup_and_one_measured_batch_completed",
        "first_micro_benchmark_completed",
        True,
    ),
    "collect": ModeSpec(
        "collect",
        20,
        60,
        5,
        20,
        "log_status_and_end_marker_collected",
        "collected",
        False,
    ),
}
GLOBAL_MAX_TIMEOUT_S = 600


@dataclass(frozen=True)
class ResolvedTimeouts:
    startup_timeout_s: int
    first_result_timeout_s: int
    hard_timeout_s: int


@dataclass(frozen=True)
class PaneCandidate:
    socket: str
    session: str
    target: str
    pane_id: str
    pane_pid: int
    pane_command: str
    cwd: str
    active: bool
    dead: bool
    in_mode: bool
    srun_pid: int | None
    srun_command: str
    job_id: str
    step_id: str
    node: str
    gpu: str
    step_state: str
    job_state: str

    def to_state(self) -> dict[str, Any]:
        now = _now_iso()
        return {
            "schema_version": GPU_PANE_SCHEMA,
            "socket": self.socket,
            "target": self.target,
            "pane_id": self.pane_id,
            "pane_pid": self.pane_pid,
            "job_id": self.job_id,
            "step_id": self.step_id,
            "node": self.node,
            "repo": str(REPO_ROOT),
            "created_at": now,
            "validated_at": now,
        }

    def to_dict(self) -> dict[str, Any]:
        return {
            "socket": self.socket,
            "session": self.session,
            "target": self.target,
            "pane_id": self.pane_id,
            "pane_pid": self.pane_pid,
            "pane_command": self.pane_command,
            "cwd": self.cwd,
            "active": self.active,
            "dead": self.dead,
            "in_mode": self.in_mode,
            "srun_pid": self.srun_pid,
            "srun_command": self.srun_command,
            "job_id": self.job_id,
            "step_id": self.step_id,
            "node": self.node,
            "gpu": self.gpu,
            "step_state": self.step_state,
            "job_state": self.job_state,
        }


@dataclass(frozen=True)
class InvalidPane:
    socket: str
    target: str
    pane_id: str
    reason: str
    pane_command: str = ""
    cwd: str = ""

    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


@dataclass(frozen=True)
class DiscoveryResult:
    candidates: tuple[PaneCandidate, ...]
    invalid: tuple[InvalidPane, ...]
    sockets_considered: tuple[str, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "candidates": [candidate.to_dict() for candidate in self.candidates],
            "invalid_candidates": [item.to_dict() for item in self.invalid],
            "sockets_considered": list(self.sockets_considered),
        }


@dataclass(frozen=True)
class GeneratedPaths:
    run_id: str
    script: Path
    log: Path
    status: Path
    summary: Path
    report: Path

    def to_dict(self) -> dict[str, str]:
        return {
            "script": str(self.script),
            "log": str(self.log),
            "status": str(self.status),
            "summary": str(self.summary),
            "report": str(self.report),
        }


@dataclass
class BridgeOptions:
    mode: str
    stage: str | None = None
    benchmark_kind: str | None = None
    embed_batch_size: int = 512
    read_chunk_rows: int = 100_000
    group_shard_size: int = 4_096
    workers: int = 2
    bf16_enabled: bool = True
    tf32_enabled: bool = True
    grouped_text_cache_enabled: bool = True
    timeout: str = "auto"
    dry_run: bool = False
    no_send: bool = False
    strict: bool = False
    socket: str | None = None
    target: str | None = None
    run_id: str | None = None
    send_method: str = DEFAULT_SEND_METHOD


def _now_iso() -> str:
    return _dt.datetime.now(_dt.timezone.utc).astimezone().isoformat(timespec="seconds")


def _now_run_id(kind: str) -> str:
    stamp = _dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"bridge_{stamp}_{_safe_run_component(kind)}"


def _safe_run_component(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip())
    return safe.strip("_") or "run"


def resolve_timeouts(mode: str, requested: str | int = "auto") -> ResolvedTimeouts:
    spec = MODE_SPECS[mode]
    if requested == "auto":
        hard = spec.auto_timeout_s
    else:
        try:
            hard = int(requested)
        except (TypeError, ValueError) as exc:
            raise BridgeError(f"invalid timeout {requested!r}", stop_reason="target_invalid") from exc
    if hard <= 0:
        raise BridgeError("timeout must be positive", stop_reason="target_invalid")
    if hard > GLOBAL_MAX_TIMEOUT_S or hard > spec.max_timeout_s:
        raise BridgeError(
            f"timeout {hard}s exceeds {mode} safety limit {spec.max_timeout_s}s",
            stop_reason="hard_timeout",
            details={"mode": mode, "timeout": hard, "max_timeout_s": spec.max_timeout_s},
        )
    return ResolvedTimeouts(
        startup_timeout_s=min(spec.startup_timeout_s, hard),
        first_result_timeout_s=min(spec.first_result_timeout_s, hard),
        hard_timeout_s=hard,
    )


def make_generated_paths(run_id: str) -> GeneratedPaths:
    return GeneratedPaths(
        run_id=run_id,
        script=RAW_LOG_DIR / f"tmux_bridge_{run_id}.sh",
        log=RAW_LOG_DIR / f"tmux_bridge_{run_id}.log",
        status=RAW_LOG_DIR / f"tmux_bridge_{run_id}.status.json",
        summary=SUMMARY_DIR / f"tmux_bridge_{run_id}_summary.md",
        report=REPORT_DIR / f"tmux_bridge_{run_id}_report.md",
    )


def _ensure_analysis_dirs() -> None:
    for path in (RAW_LOG_DIR, SUMMARY_DIR, REPORT_DIR, RUNTIME_DIR):
        path.mkdir(parents=True, exist_ok=True)


def _atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def _write_json(path: Path, data: Mapping[str, Any]) -> None:
    _atomic_write_text(path, json.dumps(data, indent=2, sort_keys=True) + "\n")


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _default_socket_exists(path: Path) -> bool:
    try:
        return stat.S_ISSOCK(path.stat().st_mode)
    except OSError:
        return False


def _env_socket_dirs() -> list[Path]:
    raw = os.environ.get("ODCR_GPU_TMUX_SOCKET_DIRS", "")
    dirs: list[Path] = []
    for part in raw.split(os.pathsep):
        part = part.strip()
        if part:
            dirs.append(Path(part))
    return dirs


def candidate_socket_paths(uid: int | None = None) -> list[Path]:
    user_id = os.getuid() if uid is None else uid
    bases = [
        Path(f"/tmp/tmux-{user_id}") / "odcr_gpu",
        Path(f"/public/home/zhangliml/tmp/codex/tmux-{user_id}") / "odcr_gpu",
        Path(f"/run/user/{user_id}/codex-tmp/tmux-{user_id}") / "odcr_gpu",
        Path(f"/run/user/{user_id}/tmux-{user_id}") / "odcr_gpu",
    ]
    for extra in _env_socket_dirs():
        bases.append(extra if extra.name == "odcr_gpu" else extra / "odcr_gpu")
    seen: set[str] = set()
    ordered: list[Path] = []
    for path in bases:
        key = str(path)
        if key not in seen:
            seen.add(key)
            ordered.append(path)
    return ordered


def _split_tmux_row(row: str) -> tuple[str, str, str, str, int, str, str, bool, bool, bool] | None:
    parts = row.rstrip("\n").split("\t")
    if len(parts) != 10:
        return None
    session, window_index, pane_index, pane_id, pane_pid, command, cwd, active, dead, in_mode = parts
    try:
        pid = int(pane_pid)
    except ValueError:
        return None
    return (
        session,
        window_index,
        pane_index,
        pane_id,
        pid,
        command,
        cwd,
        active == "1",
        dead == "1",
        in_mode == "1",
    )


def _parse_key_values(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for key, value in re.findall(r"([A-Za-z][A-Za-z0-9_]+)=([^\s]+)", text):
        values[key] = value
    return values


@dataclass(frozen=True)
class ProcInfo:
    pid: int
    ppid: int
    args: str


def _parse_ps(text: str) -> dict[int, ProcInfo]:
    procs: dict[int, ProcInfo] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split(None, 2)
        if len(parts) < 3:
            continue
        try:
            pid = int(parts[0])
            ppid = int(parts[1])
        except ValueError:
            continue
        procs[pid] = ProcInfo(pid, ppid, parts[2])
    return procs


def _iter_descendants(root_pid: int, procs: Mapping[int, ProcInfo]) -> Iterable[ProcInfo]:
    children: dict[int, list[ProcInfo]] = {}
    for proc in procs.values():
        children.setdefault(proc.ppid, []).append(proc)
    stack = list(children.get(root_pid, ()))
    while stack:
        proc = stack.pop(0)
        yield proc
        stack.extend(children.get(proc.pid, ()))


def _is_srun_command(command: str) -> bool:
    return bool(re.search(r"(^|\s|/)srun(\s|$)", command))


def _parse_job_id(command: str) -> str | None:
    match = re.search(r"--jobid(?:=|\s+)(\d+)", command)
    return match.group(1) if match else None


def _gpu_text(step_values: Mapping[str, str], job_values: Mapping[str, str]) -> str:
    parts = [
        step_values.get("TRES", ""),
        step_values.get("TresPerNode", ""),
        job_values.get("TRES", ""),
        job_values.get("TresPerNode", ""),
    ]
    return ",".join(part for part in parts if part)


def _has_gpu_tres(text: str) -> bool:
    lowered = text.lower()
    return "gres/gpu" in lowered or "trespernode=gpu" in lowered or "gpu:" in lowered


def _is_gpu_node_or_tres(node: str, gpu: str) -> bool:
    return node.lower().startswith("gpu") or _has_gpu_tres(gpu)


def _target_matches(candidate: PaneCandidate | InvalidPane, requested: str) -> bool:
    return requested in {candidate.target, candidate.pane_id}


class TmuxGpuBridge:
    def __init__(
        self,
        *,
        runner: SubprocessRunner | None = None,
        socket_exists: Callable[[Path], bool] = _default_socket_exists,
        sleep: Callable[[float], None] = time.sleep,
        clock: Callable[[], float] = time.monotonic,
    ) -> None:
        self.runner = runner or SubprocessRunner()
        self.socket_exists = socket_exists
        self.sleep = sleep
        self.clock = clock

    def discover_socket(self, socket: Path, *, allow_in_mode: bool = False) -> DiscoveryResult:
        sockets = (str(socket),)
        if not self.socket_exists(socket):
            return DiscoveryResult((), (InvalidPane(str(socket), "", "", "socket_missing_or_not_socket"),), sockets)
        panes = self._tmux_list_panes(socket)
        ps_table = self._ps_table()
        valid: list[PaneCandidate] = []
        invalid: list[InvalidPane] = []
        for row in panes:
            candidate, problem = self._validate_row(socket, row, ps_table, allow_in_mode=allow_in_mode)
            if candidate is not None:
                valid.append(candidate)
            else:
                invalid.append(problem)
        return DiscoveryResult(tuple(valid), tuple(invalid), sockets)

    def discover_all(self, *, allow_in_mode: bool = False) -> DiscoveryResult:
        sockets = tuple(str(path) for path in candidate_socket_paths())
        all_valid: list[PaneCandidate] = []
        all_invalid: list[InvalidPane] = []
        for socket_path in candidate_socket_paths():
            result = self.discover_socket(socket_path, allow_in_mode=allow_in_mode)
            all_valid.extend(result.candidates)
            all_invalid.extend(result.invalid)
        return DiscoveryResult(tuple(all_valid), tuple(all_invalid), sockets)

    def resolve_target(self, options: BridgeOptions) -> tuple[PaneCandidate, DiscoveryResult, str]:
        cli_socket = options.socket or os.environ.get("ODCR_GPU_TMUX_SOCKET")
        cli_target = options.target or os.environ.get("ODCR_GPU_TMUX_TARGET")
        if cli_target and not cli_socket:
            raise BridgeError(
                "explicit tmux target requires --socket or ODCR_GPU_TMUX_SOCKET",
                stop_reason="target_invalid",
            )
        if cli_socket:
            result = self.discover_socket(Path(cli_socket))
            candidates = list(result.candidates)
            if cli_target:
                candidates = [candidate for candidate in candidates if _target_matches(candidate, cli_target)]
            return self._pick_unique(candidates, result, source="explicit")

        if STATE_FILE.is_file():
            state = _read_json(STATE_FILE)
            socket_value = state.get("socket")
            target_value = state.get("target") or state.get("pane_id")
            if not socket_value or not target_value:
                raise BridgeError("gpu pane state file is missing socket or target", stop_reason="target_invalid")
            result = self.discover_socket(Path(str(socket_value)))
            candidates = [
                candidate
                for candidate in result.candidates
                if _target_matches(candidate, str(target_value))
                and str(state.get("job_id", candidate.job_id)) == candidate.job_id
            ]
            if not candidates:
                raise BridgeError(
                    "gpu pane state file is stale or no longer validates",
                    stop_reason="target_invalid",
                    details={"state_file": str(STATE_FILE), "state": state, "discovery": result.to_dict()},
                )
            return self._pick_unique(candidates, result, source="state-file")

        result = self.discover_all()
        return self._pick_unique(list(result.candidates), result, source="discovery")

    def resolve_unlock_target(self, options: BridgeOptions) -> tuple[PaneCandidate, DiscoveryResult, str]:
        cli_socket = options.socket or os.environ.get("ODCR_GPU_TMUX_SOCKET")
        cli_target = options.target or os.environ.get("ODCR_GPU_TMUX_TARGET")
        if cli_target and not cli_socket:
            raise BridgeError(
                "explicit tmux target requires --socket or ODCR_GPU_TMUX_SOCKET",
                stop_reason="target_invalid",
            )
        if cli_socket:
            result = self.discover_socket(Path(cli_socket), allow_in_mode=True)
            candidates = list(result.candidates)
            if cli_target:
                candidates = [candidate for candidate in candidates if _target_matches(candidate, cli_target)]
            target, discovery, source = self._pick_unique(candidates, result, source="explicit")
            return self._require_pane_mode(target, discovery, source)

        if STATE_FILE.is_file():
            state = _read_json(STATE_FILE)
            socket_value = state.get("socket")
            target_value = state.get("target") or state.get("pane_id")
            if not socket_value or not target_value:
                raise BridgeError("gpu pane state file is missing socket or target", stop_reason="target_invalid")
            result = self.discover_socket(Path(str(socket_value)), allow_in_mode=True)
            candidates = [
                candidate
                for candidate in result.candidates
                if _target_matches(candidate, str(target_value))
                and str(state.get("job_id", candidate.job_id)) == candidate.job_id
            ]
            if not candidates:
                raise BridgeError(
                    "gpu pane state file is stale or no longer validates for unlock",
                    stop_reason="target_invalid",
                    details={"state_file": str(STATE_FILE), "state": state, "discovery": result.to_dict()},
                )
            target, discovery, source = self._pick_unique(candidates, result, source="state-file")
            return self._require_pane_mode(target, discovery, source)

        result = self.discover_all(allow_in_mode=True)
        target, discovery, source = self._pick_unique(list(result.candidates), result, source="discovery")
        return self._require_pane_mode(target, discovery, source)

    def run_mode(self, options: BridgeOptions) -> dict[str, Any]:
        if options.mode == "collect":
            if not options.run_id:
                raise BridgeError("collect requires --run-id", stop_reason="target_invalid")
            return collect_run(options.run_id)

        timeouts = resolve_timeouts(options.mode, options.timeout)
        kind = self._kind(options)
        run_id = options.run_id or _now_run_id(kind)
        paths = make_generated_paths(run_id)
        _ensure_analysis_dirs()

        if options.mode == "unlock-pane":
            try:
                return self._run_unlock_pane(options, run_id, paths, timeouts)
            except BridgeError as exc:
                return self._record_failure(paths, options.mode, timeouts, exc)

        try:
            target, discovery, target_source = self.resolve_target(options)
        except BridgeError as exc:
            return self._record_failure(paths, options.mode, timeouts, exc)
        if options.mode == "discover":
            status = self._status(
                run_id=run_id,
                kind=kind,
                success=True,
                exit_code=0,
                elapsed_s=0.0,
                timeouts=timeouts,
                first_result_seen=True,
                stop_reason="target_validated",
                metrics={"target_source": target_source, "candidate_count": len(discovery.candidates)},
            )
            self._write_local_outputs(paths, status, target, discovery, mode=options.mode)
            return {**status, "target": target.to_dict(), "discovery": discovery.to_dict(), "paths": paths.to_dict()}

        if options.mode == "validate-only":
            status = self._status(
                run_id=run_id,
                kind=kind,
                success=True,
                exit_code=0,
                elapsed_s=0.0,
                timeouts=timeouts,
                first_result_seen=True,
                stop_reason="target_validated",
                metrics={"target_source": target_source, "candidate_count": len(discovery.candidates)},
            )
            script = build_validate_only_script(run_id, paths, timeouts, target)
            write_script(paths.script, script)
            self._write_local_outputs(paths, status, target, discovery, mode=options.mode)
            self._write_state(target)
            return {**status, "target": target.to_dict(), "paths": paths.to_dict(), "sent": False}

        spec = MODE_SPECS[options.mode]
        if not spec.send_allowed:
            raise BridgeError(f"mode {options.mode} cannot send commands", stop_reason="forbidden_mode")
        script = build_script(options, run_id, paths, timeouts, target)
        write_script(paths.script, script)
        self._write_state(target)
        if options.dry_run or options.no_send:
            status = self._status(
                run_id=run_id,
                kind=kind,
                success=True,
                exit_code=0,
                elapsed_s=0.0,
                timeouts=timeouts,
                first_result_seen=False,
                stop_reason="dry_run" if options.dry_run else "no_send",
                metrics={
                    "target_source": target_source,
                    "send_command": send_line(paths, timeouts),
                    "send_method": options.send_method,
                },
            )
            self._write_local_outputs(paths, status, target, discovery, mode=options.mode)
            return {
                **status,
                "target": target.to_dict(),
                "paths": paths.to_dict(),
                "sent": False,
                "send_command": send_line(paths, timeouts),
                "send_method": options.send_method,
            }

        command = send_line(paths, timeouts)
        self._send_keys(target, command, options.send_method)
        capture_after_send = self._capture_diagnostics(target, paths.run_id, command, "after_send")
        status = self._poll_for_result(paths, options.mode, timeouts)
        capture_after_poll = self._capture_diagnostics(target, paths.run_id, command, "after_poll")
        status = self._augment_status(
            paths,
            status,
            {
                "target_source": target_source,
                "send_command": command,
                "send_method": options.send_method,
                "capture_after_send": capture_after_send,
                "capture_after_poll": capture_after_poll,
            },
        )
        self._write_summary_report(paths, status, target, DiscoveryResult((target,), (), (target.socket,)), options.mode)
        return {**status, "target": target.to_dict(), "paths": paths.to_dict(), "sent": True, "send_method": options.send_method}

    def _pick_unique(
        self,
        candidates: Sequence[PaneCandidate],
        discovery: DiscoveryResult,
        *,
        source: str,
    ) -> tuple[PaneCandidate, DiscoveryResult, str]:
        if len(candidates) == 1:
            return candidates[0], discovery, source
        if len(candidates) == 0:
            raise BridgeError(
                "no validated GPU tmux pane was found",
                stop_reason="target_not_unique",
                details=discovery.to_dict(),
            )
        raise BridgeError(
            "more than one validated GPU tmux pane was found",
            stop_reason="target_not_unique",
            details=discovery.to_dict(),
        )

    def _require_pane_mode(
        self,
        target: PaneCandidate,
        discovery: DiscoveryResult,
        source: str,
    ) -> tuple[PaneCandidate, DiscoveryResult, str]:
        if target.in_mode:
            return target, discovery, source
        raise BridgeError(
            "unlock-pane requires the validated target pane to be in tmux pane mode",
            stop_reason="target_invalid",
            details={"target": target.to_dict(), "discovery": discovery.to_dict(), "target_source": source},
        )

    def _tmux_list_panes(self, socket: Path) -> list[tuple[str, str, str, str, int, str, str, bool, bool, bool]]:
        result = self.runner.run(
            ["tmux", "-S", str(socket), "list-panes", "-a", "-F", TMUX_PANE_FORMAT],
            timeout=5,
        )
        if result.returncode != 0:
            return []
        rows: list[tuple[str, str, str, str, int, str, str, bool, bool, bool]] = []
        for line in result.stdout.splitlines():
            row = _split_tmux_row(line)
            if row is not None:
                rows.append(row)
        return rows

    def _ps_table(self) -> dict[int, ProcInfo]:
        result = self.runner.run(["ps", "-e", "-o", "pid=", "-o", "ppid=", "-o", "args="], timeout=5)
        if result.returncode != 0:
            return {}
        return _parse_ps(result.stdout)

    def _validate_row(
        self,
        socket: Path,
        row: tuple[str, str, str, str, int, str, str, bool, bool, bool],
        ps_table: Mapping[int, ProcInfo],
        *,
        allow_in_mode: bool = False,
    ) -> tuple[PaneCandidate | None, InvalidPane]:
        session, window_index, pane_index, pane_id, pane_pid, command, cwd, active, dead, in_mode = row
        target = f"{session}:{window_index}.{pane_index}"
        base_invalid = InvalidPane(str(socket), target, pane_id, "invalid", command, cwd)
        if session != "odcr":
            return None, dataclasses.replace(base_invalid, reason="session_not_odcr")
        if cwd != str(REPO_ROOT):
            return None, dataclasses.replace(base_invalid, reason="cwd_not_repo")
        if dead:
            return None, dataclasses.replace(base_invalid, reason="pane_dead")
        if in_mode and not allow_in_mode:
            return None, dataclasses.replace(base_invalid, reason="pane_in_mode")

        srun_pid, srun_command = self._find_srun(pane_pid, command, ps_table)
        if not srun_command:
            return None, dataclasses.replace(base_invalid, reason="no_child_srun")
        job_id = _parse_job_id(srun_command)
        if not job_id:
            return None, dataclasses.replace(base_invalid, reason="srun_jobid_missing")

        step_id = f"{job_id}.0"
        step_result = self.runner.run(["scontrol", "show", "step", step_id], timeout=8)
        if step_result.returncode != 0:
            return None, dataclasses.replace(base_invalid, reason="scontrol_step_failed")
        job_result = self.runner.run(["scontrol", "show", "job", job_id], timeout=8)
        if job_result.returncode != 0:
            return None, dataclasses.replace(base_invalid, reason="scontrol_job_failed")

        step_values = _parse_key_values(step_result.stdout)
        job_values = _parse_key_values(job_result.stdout)
        step_state = step_values.get("State", "")
        job_state = job_values.get("JobState", "")
        node = step_values.get("NodeList") or job_values.get("NodeList") or ""
        gpu = _gpu_text(step_values, job_values)
        if step_state != "RUNNING":
            return None, dataclasses.replace(base_invalid, reason="step_not_running")
        if not _is_gpu_node_or_tres(node, gpu):
            return None, dataclasses.replace(base_invalid, reason="not_gpu_node_or_tres")
        if not _has_gpu_tres(gpu):
            return None, dataclasses.replace(base_invalid, reason="gpu_tres_missing")

        return (
            PaneCandidate(
                socket=str(socket),
                session=session,
                target=target,
                pane_id=pane_id,
                pane_pid=pane_pid,
                pane_command=command,
                cwd=cwd,
                active=active,
                dead=dead,
                in_mode=in_mode,
                srun_pid=srun_pid,
                srun_command=srun_command,
                job_id=job_id,
                step_id=step_id,
                node=node,
                gpu=gpu,
                step_state=step_state,
                job_state=job_state,
            ),
            base_invalid,
        )

    def _run_unlock_pane(
        self,
        options: BridgeOptions,
        run_id: str,
        paths: GeneratedPaths,
        timeouts: ResolvedTimeouts,
    ) -> dict[str, Any]:
        target, discovery, target_source = self.resolve_unlock_target(options)
        script = build_unlock_pane_evidence_script(run_id, paths, timeouts, target)
        write_script(paths.script, script)

        attempts: list[dict[str, Any]] = []
        final_target = target
        success = False
        for index, operation in enumerate(UNLOCK_OPERATIONS, start=1):
            result = self._unlock_pane_once(target, operation)
            relaxed_target, relaxed_discovery = self._find_same_target(target, allow_in_mode=True)
            strict_target, _strict_discovery = self._find_same_target(target, allow_in_mode=False)
            final_target = relaxed_target or strict_target or final_target
            attempt = {
                "attempt": index,
                "operation": operation,
                "args": list(result.args),
                "returncode": result.returncode,
                "stdout": result.stdout,
                "stderr": result.stderr,
                "post_relaxed_candidate_found": relaxed_target is not None,
                "post_strict_validate_success": strict_target is not None,
                "post_pane_in_mode": relaxed_target.in_mode if relaxed_target is not None else None,
                "post_discovery": relaxed_discovery.to_dict(),
            }
            attempts.append(attempt)
            if result.returncode != 0:
                break
            if strict_target is not None:
                final_target = strict_target
                success = True
                break

        status = self._status(
            run_id=run_id,
            kind="unlock-pane",
            success=success,
            exit_code=0 if success else 1,
            elapsed_s=0.0,
            timeouts=timeouts,
            first_result_seen=True,
            stop_reason=MODE_SPECS["unlock-pane"].stop_reason_success if success else "pane_in_mode_unlock_failed",
            metrics={
                "target_source": target_source,
                "initial_pane_in_mode": target.in_mode,
                "final_pane_in_mode": final_target.in_mode,
                "attempt_count": len(attempts),
                "attempts": attempts,
            },
        )
        self._write_unlock_outputs(paths, status, target, final_target, discovery, attempts)
        if success:
            self._write_state(final_target)
        return {
            **status,
            "target": final_target.to_dict(),
            "paths": paths.to_dict(),
            "sent": False,
            "unlock_operations": [attempt["operation"] for attempt in attempts],
        }

    def _unlock_pane_once(self, target: PaneCandidate, operation: str) -> CommandResult:
        if operation == "copy-mode-cancel":
            args = ["tmux", "-S", target.socket, "send-keys", "-t", target.pane_id, "-X", "cancel"]
        elif operation == "escape":
            args = ["tmux", "-S", target.socket, "send-keys", "-t", target.pane_id, "Escape"]
        else:
            raise BridgeError(f"unsupported unlock operation: {operation}", stop_reason="forbidden_mode")
        return self.runner.run(args, timeout=5)

    def _find_same_target(
        self,
        target: PaneCandidate,
        *,
        allow_in_mode: bool,
    ) -> tuple[PaneCandidate | None, DiscoveryResult]:
        discovery = self.discover_socket(Path(target.socket), allow_in_mode=allow_in_mode)
        for candidate in discovery.candidates:
            if (
                candidate.pane_id == target.pane_id
                and candidate.target == target.target
                and candidate.job_id == target.job_id
            ):
                return candidate, discovery
        return None, discovery

    def _find_srun(
        self,
        pane_pid: int,
        pane_command: str,
        ps_table: Mapping[int, ProcInfo],
    ) -> tuple[int | None, str]:
        if _is_srun_command(pane_command):
            proc = ps_table.get(pane_pid)
            if proc and _parse_job_id(proc.args):
                return proc.pid, proc.args
        for proc in _iter_descendants(pane_pid, ps_table):
            if _is_srun_command(proc.args) and _parse_job_id(proc.args):
                return proc.pid, proc.args
        return None, ""

    def _send_keys(self, target: PaneCandidate, command: str, send_method: str = DEFAULT_SEND_METHOD) -> None:
        if send_method not in SEND_METHODS:
            raise BridgeError(f"unsupported send method: {send_method}", stop_reason="target_invalid")
        if "\n" in command or "\r" in command:
            raise BridgeError("generated send command must be a single line", stop_reason="forbidden_mode")

        if send_method == "target-name-literal-enter":
            commands = (
                ("literal", ["tmux", "-S", target.socket, "send-keys", "-t", target.target, "-l", command]),
                ("enter", ["tmux", "-S", target.socket, "send-keys", "-t", target.target, "Enter"]),
            )
        elif send_method == "pane-id-literal-cm":
            commands = (
                ("literal", ["tmux", "-S", target.socket, "send-keys", "-t", target.pane_id, "-l", command]),
                ("enter", ["tmux", "-S", target.socket, "send-keys", "-t", target.pane_id, "C-m"]),
            )
        elif send_method == "buffer-paste-enter":
            commands = (
                ("set_buffer", ["tmux", "-S", target.socket, "set-buffer", command]),
                ("paste_buffer", ["tmux", "-S", target.socket, "paste-buffer", "-t", target.pane_id]),
                ("enter", ["tmux", "-S", target.socket, "send-keys", "-t", target.pane_id, "Enter"]),
            )
        else:
            commands = (
                ("literal", ["tmux", "-S", target.socket, "send-keys", "-t", target.pane_id, "-l", command]),
                ("enter", ["tmux", "-S", target.socket, "send-keys", "-t", target.pane_id, "Enter"]),
            )

        results = [(label, self.runner.run(args, timeout=5)) for label, args in commands]
        failed = [(label, result) for label, result in results if result.returncode != 0]
        if failed:
            raise BridgeError(
                "tmux send-keys failed",
                stop_reason="target_invalid",
                details={
                    "send_method": send_method,
                    "failed_steps": [
                        {
                            "step": label,
                            "args": list(result.args),
                            "stdout": result.stdout,
                            "stderr": result.stderr,
                            "returncode": result.returncode,
                        }
                        for label, result in failed
                    ],
                },
            )

    def _capture_diagnostics(self, target: PaneCandidate, run_id: str, command: str, phase: str) -> dict[str, Any]:
        result = self.runner.run(
            ["tmux", "-S", target.socket, "capture-pane", "-t", target.pane_id, "-p", "-S", "-120"],
            timeout=5,
        )
        text = result.stdout if result.returncode == 0 else ""
        lines = [line.rstrip() for line in text.splitlines() if line.strip()]
        recent_lines = lines[-12:]
        prompt_seen = any(line.endswith("$") and "bash" in line for line in recent_lines)
        return {
            "phase": phase,
            "capture_target": target.pane_id,
            "returncode": result.returncode,
            "stderr": result.stderr,
            "run_id_seen": run_id in text,
            "command_seen": command in text or Path(command.split()[-1]).name in text,
            "begin_marker_seen": f"ODCR_BRIDGE_BEGIN_{run_id}" in text,
            "end_marker_seen": f"ODCR_BRIDGE_END_{run_id}" in text,
            "bash_prompt_seen": prompt_seen,
            "last_nonempty_line": recent_lines[-1] if recent_lines else "",
        }

    def _augment_status(self, paths: GeneratedPaths, status: Mapping[str, Any], extra_metrics: Mapping[str, Any]) -> dict[str, Any]:
        augmented = dict(status)
        metrics = dict(augmented.get("metrics") or {})
        metrics.update(extra_metrics)
        augmented["metrics"] = metrics
        _write_json(paths.status, augmented)
        return augmented

    def _record_failure(
        self,
        paths: GeneratedPaths,
        mode: str,
        timeouts: ResolvedTimeouts,
        exc: BridgeError,
    ) -> dict[str, Any]:
        status = self._status(
            run_id=paths.run_id,
            kind=mode,
            success=False,
            exit_code=1,
            elapsed_s=0.0,
            timeouts=timeouts,
            first_result_seen=False,
            stop_reason=exc.stop_reason,
            metrics={"error": str(exc), "details": exc.details},
        )
        write_script(paths.script, build_failure_evidence_script(paths.run_id, paths, mode, str(exc)))
        self._write_failure_outputs(paths, status, mode)
        return {**status, "paths": paths.to_dict(), "sent": False}

    def _poll_for_result(self, paths: GeneratedPaths, mode: str, timeouts: ResolvedTimeouts) -> dict[str, Any]:
        start = self.clock()
        begin_seen = False
        while True:
            elapsed = self.clock() - start
            log_text = paths.log.read_text(encoding="utf-8") if paths.log.is_file() else ""
            begin_seen = begin_seen or f"ODCR_BRIDGE_BEGIN_{paths.run_id}" in log_text
            if paths.status.is_file():
                try:
                    status = _read_json(paths.status)
                except json.JSONDecodeError:
                    status = None
                if isinstance(status, dict):
                    return status
            if not begin_seen and elapsed > timeouts.startup_timeout_s:
                return self._write_timeout_status(paths, mode, timeouts, "startup_timeout", elapsed)
            if begin_seen and elapsed > timeouts.first_result_timeout_s:
                return self._write_timeout_status(paths, mode, timeouts, "first_result_timeout", elapsed)
            if elapsed > timeouts.hard_timeout_s:
                return self._write_timeout_status(paths, mode, timeouts, "hard_timeout", elapsed)
            self.sleep(0.5)

    def _write_timeout_status(
        self,
        paths: GeneratedPaths,
        mode: str,
        timeouts: ResolvedTimeouts,
        stop_reason: str,
        elapsed: float,
    ) -> dict[str, Any]:
        if not paths.log.is_file():
            _atomic_write_text(
                paths.log,
                "\n".join(
                    (
                        f"run_id={paths.run_id}",
                        f"mode={mode}",
                        f"stop_reason={stop_reason}",
                        "bridge_script_begin_marker_seen=false",
                        "bridge_script_end_marker_seen=false",
                        "",
                    )
                ),
            )
        status = self._status(
            run_id=paths.run_id,
            kind=mode,
            success=False,
            exit_code=124,
            elapsed_s=round(elapsed, 3),
            timeouts=timeouts,
            first_result_seen=False,
            stop_reason=stop_reason,
            metrics={},
        )
        _write_json(paths.status, status)
        return status

    def _status(
        self,
        *,
        run_id: str,
        kind: str,
        success: bool,
        exit_code: int,
        elapsed_s: float,
        timeouts: ResolvedTimeouts,
        first_result_seen: bool,
        stop_reason: str,
        metrics: Mapping[str, Any],
    ) -> dict[str, Any]:
        spec = MODE_SPECS[kind if kind in MODE_SPECS else kind.split("_")[0]]
        return {
            "schema_version": BRIDGE_STATUS_SCHEMA,
            "run_id": run_id,
            "kind": kind,
            "success": bool(success),
            "exit_code": int(exit_code),
            "elapsed_s": float(elapsed_s),
            "startup_timeout_s": timeouts.startup_timeout_s,
            "first_result_timeout_s": timeouts.first_result_timeout_s,
            "hard_timeout_s": timeouts.hard_timeout_s,
            "first_result_seen": bool(first_result_seen),
            "success_condition": spec.success_condition,
            "stop_reason": stop_reason,
            "metrics": dict(metrics),
        }

    def _write_state(self, target: PaneCandidate) -> None:
        _write_json(STATE_FILE, target.to_state())

    def _write_local_outputs(
        self,
        paths: GeneratedPaths,
        status: Mapping[str, Any],
        target: PaneCandidate,
        discovery: DiscoveryResult,
        *,
        mode: str,
    ) -> None:
        log_lines = [
            f"ODCR_BRIDGE_BEGIN_{paths.run_id}",
            f"mode={mode}",
            f"target={target.socket}:{target.target}",
            f"job={target.job_id}",
            f"step={target.step_id}",
            f"node={target.node}",
            f"gpu={target.gpu}",
            f"stop_reason={status.get('stop_reason')}",
            f"ODCR_BRIDGE_END_{paths.run_id}",
            "",
        ]
        _atomic_write_text(paths.log, "\n".join(log_lines))
        _write_json(paths.status, status)
        self._write_summary_report(paths, status, target, discovery, mode)

    def _write_summary_report(
        self,
        paths: GeneratedPaths,
        status: Mapping[str, Any],
        target: PaneCandidate,
        discovery: DiscoveryResult,
        mode: str,
    ) -> None:
        summary = textwrap.dedent(
            f"""\
            # Tmux Bridge {paths.run_id} Summary

            - mode: {mode}
            - success: {status.get("success")}
            - stop_reason: {status.get("stop_reason")}
            - target: {target.socket}:{target.target}
            - pane_id: {target.pane_id}
            - job_id: {target.job_id}
            - step_id: {target.step_id}
            - node: {target.node}
            - gpu: {target.gpu}
            - first_result_seen: {status.get("first_result_seen")}
            - hard_timeout_s: {status.get("hard_timeout_s")}
            """
        )
        report = textwrap.dedent(
            f"""\
            # Tmux Bridge {paths.run_id} Report

            ## Result

            Status: {status.get("success")}
            Stop reason: {status.get("stop_reason")}
            Mode: {mode}
            Success condition: {status.get("success_condition")}

            ## Target

            ```json
            {json.dumps(target.to_dict(), indent=2, sort_keys=True)}
            ```

            ## Status

            ```json
            {json.dumps(dict(status), indent=2, sort_keys=True)}
            ```

            ## Discovery

            Valid candidates: {len(discovery.candidates)}
            Invalid candidates: {len(discovery.invalid)}

            ## Boundaries

            - No formal preprocess_a/b/c was started.
            - No Step3/Step4/Step5 was entered.
            - No eval/rerank was run.
            - No GPU allocation command was executed by Codex.
            - No tmux session was created, killed, switched, or attached.
            """
        )
        _atomic_write_text(paths.summary, summary)
        _atomic_write_text(paths.report, report)

    def _write_unlock_outputs(
        self,
        paths: GeneratedPaths,
        status: Mapping[str, Any],
        initial_target: PaneCandidate,
        final_target: PaneCandidate,
        discovery: DiscoveryResult,
        attempts: Sequence[Mapping[str, Any]],
    ) -> None:
        log_lines = [
            f"ODCR_BRIDGE_BEGIN_{paths.run_id}",
            "mode=unlock-pane",
            f"target={initial_target.socket}:{initial_target.target}",
            f"pane_id={initial_target.pane_id}",
            f"initial_pane_in_mode={initial_target.in_mode}",
            f"final_pane_in_mode={final_target.in_mode}",
            f"stop_reason={status.get('stop_reason')}",
        ]
        for attempt in attempts:
            log_lines.append(
                "unlock_attempt="
                + json.dumps(
                    {
                        "attempt": attempt.get("attempt"),
                        "operation": attempt.get("operation"),
                        "returncode": attempt.get("returncode"),
                        "post_strict_validate_success": attempt.get("post_strict_validate_success"),
                        "post_pane_in_mode": attempt.get("post_pane_in_mode"),
                    },
                    sort_keys=True,
                )
            )
        log_lines.extend((f"ODCR_BRIDGE_END_{paths.run_id}", ""))
        _atomic_write_text(paths.log, "\n".join(log_lines))
        _write_json(paths.status, status)
        self._write_summary_report(paths, status, final_target, discovery, "unlock-pane")

    def _write_failure_outputs(self, paths: GeneratedPaths, status: Mapping[str, Any], mode: str) -> None:
        log_lines = [
            f"ODCR_BRIDGE_BEGIN_{paths.run_id}",
            f"mode={mode}",
            "sent=false",
            f"stop_reason={status.get('stop_reason')}",
            f"error={status.get('metrics', {}).get('error', '')}",
            f"ODCR_BRIDGE_END_{paths.run_id}",
            "",
        ]
        _atomic_write_text(paths.log, "\n".join(log_lines))
        _write_json(paths.status, status)
        summary = textwrap.dedent(
            f"""\
            # Tmux Bridge {paths.run_id} Summary

            - mode: {mode}
            - success: {status.get("success")}
            - stop_reason: {status.get("stop_reason")}
            - sent: false
            """
        )
        report = textwrap.dedent(
            f"""\
            # Tmux Bridge {paths.run_id} Report

            ## Result

            Status: {status.get("success")}
            Stop reason: {status.get("stop_reason")}
            Mode: {mode}

            ## Status

            ```json
            {json.dumps(dict(status), indent=2, sort_keys=True)}
            ```

            ## Boundaries

            - No target-pane shell command was sent.
            - No formal preprocess_a/b/c was started.
            - No Step3/Step4/Step5 was entered.
            - No eval/rerank was run.
            - No GPU allocation command was executed by Codex.
            - No tmux session was created, killed, switched, or attached.
            """
        )
        _atomic_write_text(paths.summary, summary)
        _atomic_write_text(paths.report, report)

    def _kind(self, options: BridgeOptions) -> str:
        if options.mode == "preprocess-dryrun":
            return options.mode
        if options.mode == "micro-benchmark":
            return options.mode
        return options.mode


def build_unlock_pane_evidence_script(
    run_id: str,
    paths: GeneratedPaths,
    timeouts: ResolvedTimeouts,
    target: PaneCandidate,
) -> str:
    del paths, timeouts
    return textwrap.dedent(
        f"""\
        #!/usr/bin/env bash
        # Evidence stub for controlled unlock-pane run {run_id}.
        # The bridge does not run this file in the target pane.
        # Fixed operations are performed by odcr_tmux_gpu_bridge.py only:
        # tmux -S {target.socket} send-keys -t {target.pane_id} -X cancel
        # tmux -S {target.socket} send-keys -t {target.pane_id} Escape
        exit 0
        """
    )


def build_failure_evidence_script(run_id: str, paths: GeneratedPaths, mode: str, error: str) -> str:
    del paths, error
    return textwrap.dedent(
        f"""\
        #!/usr/bin/env bash
        # Evidence stub for bridge failure {run_id}.
        # Mode: {mode}
        # No target-pane shell command was sent.
        exit 1
        """
    )


def send_line(paths: GeneratedPaths, timeouts: ResolvedTimeouts) -> str:
    try:
        script_path = paths.script.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        script_path = str(paths.script)
    return f"timeout {timeouts.hard_timeout_s}s bash {script_path}"


def write_script(path: Path, script: str) -> None:
    validate_script_safety(script)
    _atomic_write_text(path, script)
    path.chmod(0o700)


def validate_script_safety(script: str) -> None:
    lowered = script.lower()
    forbidden_regexes = [
        (r"\bnohup\b", "nohup"),
        (r"&", "background_or_fd_ampersand"),
        (r"\bdisown\b", "disown"),
        (r"\bsbatch\b", "sbatch"),
        (r"\bsrun\b", "srun"),
        (r"\bscancel\b", "scancel"),
        (r"\bodcr-enter-gpu\b", "odcr-enter-gpu"),
        (r"\brm\s+-rf\b", "rm -rf"),
        (r"\bkill\b", "kill"),
        (r"\bpkill\b", "pkill"),
        (r"\bmv\s+data\b", "mv data"),
        (r"\brm\s+data\b", "rm data"),
        (r"\brm\s+merged\b", "rm merged"),
        (r"\bstep3\b", "step3"),
        (r"\bstep4\b", "step4"),
        (r"\bstep5\b", "step5"),
    ]
    for pattern, label in forbidden_regexes:
        if re.search(pattern, lowered):
            raise BridgeError(f"generated bridge script contains forbidden token: {label}", stop_reason="forbidden_mode")
    if re.search(r"\./odcr\s+preprocess\s+a\b", lowered):
        raise BridgeError("preprocess a is forbidden", stop_reason="forbidden_mode")
    for stage in ("b", "c"):
        for match in re.finditer(rf"\./odcr\s+preprocess\s+{stage}\b[^\n]*", lowered):
            if "--dry-run" not in match.group(0):
                raise BridgeError(f"preprocess {stage} without --dry-run is forbidden", stop_reason="forbidden_mode")
    if re.search(r"(?:\./odcr|python\s+code/odcr\.py)\s+eval\b", lowered):
        raise BridgeError("eval is forbidden", stop_reason="forbidden_mode")
    if re.search(r"(?:\./odcr|python\s+code/odcr\.py)\s+rerank\b", lowered):
        raise BridgeError("rerank is forbidden", stop_reason="forbidden_mode")
    if re.search(r"\b(?:data|merged)/", lowered):
        raise BridgeError("formal data/merged writes are forbidden in bridge scripts", stop_reason="forbidden_mode")


def _script_header(paths: GeneratedPaths) -> str:
    return textwrap.dedent(
        f"""\
        #!/usr/bin/env bash
        set -euo pipefail
        cd {REPO_ROOT}
        export TMPDIR={SAFE_TMPDIR}
        export TMP="$TMPDIR"
        export TEMP="$TMPDIR"
        export HF_HUB_OFFLINE=1
        export TRANSFORMERS_OFFLINE=1
        export HF_EVALUATE_OFFLINE=1
        LOG={paths.log}
        STATUS={paths.status}
        PYTHON={D4C_PYTHON}
        """
    )


def _marker_script_header(paths: GeneratedPaths) -> str:
    return textwrap.dedent(
        f"""\
        #!/usr/bin/env bash
        set -euo pipefail
        cd {REPO_ROOT}
        export TMPDIR={SAFE_TMPDIR}
        export TMP="$TMPDIR"
        export TEMP="$TMPDIR"
        LOG={paths.log}
        STATUS={paths.status}
        mkdir -p "$(dirname "$LOG")" "$(dirname "$STATUS")"
        : > "$LOG"
        """
    )


def _python_common_prelude(paths: GeneratedPaths, run_id: str, kind: str, timeouts: ResolvedTimeouts, success_condition: str) -> str:
    return f"""
import json
import os
import socket
import subprocess
import sys
import time
import traceback
from pathlib import Path

RUN_ID = {run_id!r}
KIND = {kind!r}
LOG_PATH = Path({str(paths.log)!r})
STATUS_PATH = Path({str(paths.status)!r})
SUCCESS_CONDITION = {success_condition!r}
STARTUP_TIMEOUT_S = {timeouts.startup_timeout_s}
FIRST_RESULT_TIMEOUT_S = {timeouts.first_result_timeout_s}
HARD_TIMEOUT_S = {timeouts.hard_timeout_s}
SCHEMA = {BRIDGE_STATUS_SCHEMA!r}
START = time.monotonic()
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
STATUS_PATH.parent.mkdir(parents=True, exist_ok=True)
LOG = LOG_PATH.open("a", encoding="utf-8")

def emit(*parts):
    line = " ".join(str(part) for part in parts)
    print(line, flush=True)
    LOG.write(line + "\\n")
    LOG.flush()

def finish(success, exit_code, stop_reason, metrics=None, first_result_seen=False):
    elapsed = round(time.monotonic() - START, 3)
    status = {{
        "schema_version": SCHEMA,
        "run_id": RUN_ID,
        "kind": KIND,
        "success": bool(success),
        "exit_code": int(exit_code),
        "elapsed_s": elapsed,
        "startup_timeout_s": STARTUP_TIMEOUT_S,
        "first_result_timeout_s": FIRST_RESULT_TIMEOUT_S,
        "hard_timeout_s": HARD_TIMEOUT_S,
        "first_result_seen": bool(first_result_seen),
        "success_condition": SUCCESS_CONDITION,
        "stop_reason": stop_reason,
        "metrics": metrics or {{}},
    }}
    STATUS_PATH.write_text(json.dumps(status, indent=2, sort_keys=True) + "\\n", encoding="utf-8")
    return int(exit_code)

def run_cmd(args):
    emit("$", " ".join(args))
    proc = subprocess.run(args, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if proc.stdout:
        for line in proc.stdout.splitlines():
            emit(line)
    if proc.returncode != 0:
        raise RuntimeError("command failed: " + " ".join(args))
    return proc.stdout
"""


def build_validate_only_script(
    run_id: str,
    paths: GeneratedPaths,
    timeouts: ResolvedTimeouts,
    target: PaneCandidate,
) -> str:
    spec = MODE_SPECS["validate-only"]
    body = _python_common_prelude(paths, run_id, "validate-only", timeouts, spec.success_condition)
    body += f"""
exit_code = 0
try:
    emit("ODCR_BRIDGE_BEGIN_" + RUN_ID)
    emit("validate_only_target", {target.socket!r}, {target.target!r})
    emit("validate_only_job", {target.job_id!r}, {target.step_id!r}, {target.node!r})
    emit("ODCR_BRIDGE_END_" + RUN_ID)
    exit_code = finish(True, 0, {spec.stop_reason_success!r}, {{"node": {target.node!r}, "gpu": {target.gpu!r}}}, True)
except Exception as exc:
    emit("bridge_error", repr(exc))
    emit(traceback.format_exc())
    emit("ODCR_BRIDGE_END_" + RUN_ID)
    exit_code = finish(False, 1, "script_exit_nonzero", {{"error": repr(exc)}}, False)
finally:
    LOG.close()
sys.exit(exit_code)
"""
    return _script_header(paths) + f'"$PYTHON" - <<\'PY\'\n{body}\nPY\n'


def build_marker_probe_script(
    run_id: str,
    paths: GeneratedPaths,
    timeouts: ResolvedTimeouts,
    _target: PaneCandidate,
) -> str:
    spec = MODE_SPECS["marker-probe"]
    status = {
        "schema_version": BRIDGE_STATUS_SCHEMA,
        "run_id": run_id,
        "kind": "marker-probe",
        "success": True,
        "exit_code": 0,
        "elapsed_s": 0.0,
        "startup_timeout_s": timeouts.startup_timeout_s,
        "first_result_timeout_s": timeouts.first_result_timeout_s,
        "hard_timeout_s": timeouts.hard_timeout_s,
        "first_result_seen": True,
        "success_condition": spec.success_condition,
        "stop_reason": spec.stop_reason_success,
        "metrics": {"send_marker": f"ODCR_BRIDGE_SEND_OK_{run_id}"},
    }
    status_json = json.dumps(status, indent=2, sort_keys=True)
    body = f"""emit() {{
  line="$*"
  printf '%s\\n' "$line" | tee -a "$LOG"
}}
emit "ODCR_BRIDGE_BEGIN_{run_id}"
emit '$ hostname'
host_out="$(hostname)"
emit "$host_out"
emit '$ pwd'
pwd_out="$(pwd)"
emit "$pwd_out"
emit "ODCR_BRIDGE_SEND_OK_{run_id}"
cat > "$STATUS" <<'JSON'
{status_json}
JSON
emit "ODCR_BRIDGE_END_{run_id}"
"""
    return _marker_script_header(paths) + body


def build_cuda_probe_script(
    run_id: str,
    paths: GeneratedPaths,
    timeouts: ResolvedTimeouts,
    _target: PaneCandidate,
) -> str:
    spec = MODE_SPECS["cuda-probe"]
    body = _python_common_prelude(paths, run_id, "cuda-probe", timeouts, spec.success_condition)
    body += f"""
exit_code = 0
try:
    emit("ODCR_BRIDGE_BEGIN_" + RUN_ID)
    host_out = run_cmd(["hostname"]).strip()
    emit("$", "pwd")
    emit(os.getcwd())
    emit("TMUX=" + os.environ.get("TMUX", "UNSET"))
    emit("SLURM_JOB_ID=" + os.environ.get("SLURM_JOB_ID", "UNSET"))
    emit("TMPDIR=" + os.environ.get("TMPDIR", "UNSET"))
    emit("XDG_RUNTIME_DIR=" + os.environ.get("XDG_RUNTIME_DIR", "UNSET"))
    run_cmd(["which", "python"])
    smi = run_cmd(["nvidia-smi", "-L"])
    import torch
    cuda_available = bool(torch.cuda.is_available())
    device_count = int(torch.cuda.device_count())
    device_names = [torch.cuda.get_device_name(i) for i in range(device_count)]
    emit("torch_cuda_available", cuda_available)
    emit("torch_device_count", device_count)
    for idx, name in enumerate(device_names):
        emit("torch_device", idx, name)
    metrics = {{
        "hostname": host_out,
        "cuda_available": cuda_available,
        "device_count": device_count,
        "device_names": device_names,
        "nvidia_smi_lines": [line for line in smi.splitlines() if line.strip()],
    }}
    if not cuda_available or device_count < 1 or not device_names:
        emit("ODCR_BRIDGE_END_" + RUN_ID)
        exit_code = finish(False, 2, "cuda_unavailable", metrics, False)
    else:
        emit("ODCR_BRIDGE_END_" + RUN_ID)
        exit_code = finish(True, 0, {spec.stop_reason_success!r}, metrics, True)
except Exception as exc:
    emit("bridge_error", repr(exc))
    emit(traceback.format_exc())
    emit("ODCR_BRIDGE_END_" + RUN_ID)
    exit_code = finish(False, 1, "script_exit_nonzero", {{"error": repr(exc)}}, False)
finally:
    LOG.close()
sys.exit(exit_code)
"""
    return _script_header(paths) + f'"$PYTHON" - <<\'PY\'\n{body}\nPY\n'


def _model_path_reader_body() -> str:
    return """
def read_sentence_model_path():
    import yaml
    cfg_path = Path("configs/odcr.yaml")
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    env = cfg.get("env") or {}
    value = env.get("sentence_embed_model")
    if not value:
        raise RuntimeError("configs/odcr.yaml env.sentence_embed_model is required")
    return str(value)

def read_embed_dim():
    import yaml
    cfg_path = Path("configs/odcr.yaml")
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    env = cfg.get("env") or {}
    value = env.get("embed_dim")
    if value is None:
        raise RuntimeError("configs/odcr.yaml env.embed_dim is required")
    return int(value)
"""


def build_bge_smoke_script(
    run_id: str,
    paths: GeneratedPaths,
    timeouts: ResolvedTimeouts,
    _target: PaneCandidate,
) -> str:
    spec = MODE_SPECS["bge-smoke"]
    body = _python_common_prelude(paths, run_id, "bge-smoke", timeouts, spec.success_condition)
    body += _model_path_reader_body()
    body += f"""
exit_code = 0
try:
    emit("ODCR_BRIDGE_BEGIN_" + RUN_ID)
    phase = "dependency_import"
    import numpy as np
    import torch
    import torch.nn.functional as F
    from transformers import AutoModel, AutoTokenizer
    phase = "cuda_check"
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is not available in the target tmux pane")
    device = torch.device("cuda")
    model_path = read_sentence_model_path()
    phase = "local_model"
    if not Path(model_path).is_dir():
        raise FileNotFoundError(f"local BGE model path does not exist: {{model_path}}")
    texts = ["ODCR short GPU smoke test.", "BGE local single batch."]
    t0 = time.monotonic()
    phase = "tokenizer_load"
    tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
    phase = "model_load"
    model = AutoModel.from_pretrained(model_path, local_files_only=True)
    model.to("cuda").eval()
    expected_hidden = read_embed_dim()
    actual_hidden = int(getattr(model.config, "hidden_size", 0))
    if actual_hidden != expected_hidden:
        raise ValueError(f"BGE hidden_size={{actual_hidden}} does not match expected smoke dim {{expected_hidden}}")
    if torch.cuda.is_available():
        torch.cuda.synchronize(device)
    load_seconds = round(time.monotonic() - t0, 3)
    t1 = time.monotonic()
    phase = "tokenize"
    encoded = tokenizer(texts, padding=True, truncation=True, max_length=512, return_tensors="pt")
    encoded = {{key: value.to(device) for key, value in encoded.items()}}
    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats(device)
    autocast_enabled = bool(torch.cuda.is_bf16_supported()) if torch.cuda.is_available() else False
    phase = "forward"
    with torch.no_grad():
        with torch.cuda.amp.autocast(dtype=torch.bfloat16, enabled=autocast_enabled):
            outputs = model(**encoded)
            # CLS pooling matches the formal preprocess_b embedding path.
            pooled = outputs.last_hidden_state[:, 0, :].to(torch.float32)
            vectors_t = F.normalize(pooled, p=2, dim=1)
    if torch.cuda.is_available():
        torch.cuda.synchronize(device)
    encode_seconds = round(time.monotonic() - t1, 3)
    vectors = vectors_t.detach().cpu().numpy()
    shape = list(vectors.shape)
    dtype = str(vectors.dtype)
    norm = float(np.linalg.norm(vectors[0]))
    memory = int(torch.cuda.max_memory_allocated()) if torch.cuda.is_available() else 0
    emit("BGE load_seconds", load_seconds)
    emit("BGE encode_seconds", encode_seconds)
    emit("BGE shape", shape)
    emit("BGE dtype", dtype)
    emit("BGE pooling", "cls")
    emit("BGE norm0", round(norm, 6))
    emit("GPU memory", memory)
    metrics = {{"load_seconds": load_seconds, "encode_seconds": encode_seconds, "shape": shape, "dtype": dtype, "pooling": "cls", "norm0": norm, "gpu_max_memory_allocated": memory, "autocast_bf16": autocast_enabled, "model_path": model_path}}
    emit("ODCR_BRIDGE_END_" + RUN_ID)
    exit_code = finish(True, 0, {spec.stop_reason_success!r}, metrics, True)
except Exception as exc:
    message = repr(exc)
    lowered = message.lower()
    if "out of memory" in lowered:
        stop_reason = "oom"
    elif phase == "dependency_import":
        stop_reason = "dependency_import_error"
    elif phase == "local_model":
        stop_reason = "local_model_missing"
    elif phase == "tokenizer_load":
        stop_reason = "tokenizer_load_failed"
    elif phase == "model_load":
        stop_reason = "model_load_failed"
    elif phase == "cuda_check":
        stop_reason = "cuda_unavailable"
    elif phase in {{"tokenize", "forward"}}:
        stop_reason = "forward_failed"
    else:
        stop_reason = "script_exit_nonzero"
    emit("bridge_error", repr(exc))
    emit(traceback.format_exc())
    emit("ODCR_BRIDGE_END_" + RUN_ID)
    exit_code = finish(False, 1, stop_reason, {{"error": repr(exc), "failure_class": stop_reason, "phase": phase}}, False)
finally:
    LOG.close()
sys.exit(exit_code)
"""
    return _script_header(paths) + f'"$PYTHON" - <<\'PY\'\n{body}\nPY\n'


def build_preprocess_dryrun_script(
    run_id: str,
    paths: GeneratedPaths,
    timeouts: ResolvedTimeouts,
    _target: PaneCandidate,
    stage: str,
) -> str:
    if stage not in {"b", "c"}:
        raise BridgeError("preprocess dry-run stage must be b or c", stop_reason="forbidden_mode")
    spec = MODE_SPECS["preprocess-dryrun"]
    command = ["./odcr", "preprocess", stage, "--dry-run"]
    body = _python_common_prelude(paths, run_id, "preprocess-dryrun", timeouts, spec.success_condition)
    body += f"""
exit_code = 0
try:
    emit("ODCR_BRIDGE_BEGIN_" + RUN_ID)
    output = run_cmd({command!r})
    expected_terms = ["gpu", "model", "batch"]
    metrics = {{"stage": {stage!r}, "output_lines": len(output.splitlines()), "contains_expected_terms": all(term in output.lower() for term in expected_terms)}}
    emit("ODCR_BRIDGE_END_" + RUN_ID)
    exit_code = finish(True, 0, {spec.stop_reason_success!r}, metrics, True)
except Exception as exc:
    emit("bridge_error", repr(exc))
    emit(traceback.format_exc())
    emit("ODCR_BRIDGE_END_" + RUN_ID)
    exit_code = finish(False, 1, "script_exit_nonzero", {{"error": repr(exc), "stage": {stage!r}}}, False)
finally:
    LOG.close()
sys.exit(exit_code)
"""
    return _script_header(paths) + f'"$PYTHON" - <<\'PY\'\n{body}\nPY\n'


def build_micro_benchmark_script(
    run_id: str,
    paths: GeneratedPaths,
    timeouts: ResolvedTimeouts,
    _target: PaneCandidate,
    benchmark_kind: str,
    *,
    embed_batch_size: int = 512,
    read_chunk_rows: int = 100_000,
    group_shard_size: int = 4_096,
    workers: int = 2,
    bf16_enabled: bool = True,
    tf32_enabled: bool = True,
    grouped_text_cache_enabled: bool = True,
) -> str:
    if benchmark_kind != "bge-single-batch":
        raise BridgeError("only bge-single-batch micro benchmark is allowed", stop_reason="forbidden_mode")
    embed_batch_size = max(1, int(embed_batch_size))
    read_chunk_rows = max(1, int(read_chunk_rows))
    group_shard_size = max(1, int(group_shard_size))
    workers = max(1, int(workers))
    spec = MODE_SPECS["micro-benchmark"]
    benchmark_config = {
        "benchmark_kind": benchmark_kind,
        "embed_batch_size": embed_batch_size,
        "read_chunk_rows": read_chunk_rows,
        "group_shard_size": group_shard_size,
        "workers": workers,
        "bf16_enabled": bool(bf16_enabled),
        "tf32_enabled": bool(tf32_enabled),
        "grouped_text_cache_enabled": bool(grouped_text_cache_enabled),
        "warmup_batches": 1,
        "measured_batches": 1,
        "loader": "transformers.AutoTokenizer/AutoModel",
        "local_files_only": True,
    }
    body = _python_common_prelude(paths, run_id, "micro-benchmark", timeouts, spec.success_condition)
    body += _model_path_reader_body()
    body += f"""
exit_code = 0
try:
    emit("ODCR_BRIDGE_BEGIN_" + RUN_ID)
    benchmark_config = {benchmark_config!r}
    phase = "dependency_import"
    import threading
    import torch
    from transformers import AutoModel, AutoTokenizer
    phase = "cuda_check"
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is not available in the target tmux pane")
    device_count = int(torch.cuda.device_count())
    device_names = [torch.cuda.get_device_name(i) for i in range(device_count)]
    if device_count < 1:
        raise RuntimeError("CUDA device_count is zero")
    torch.backends.cuda.matmul.allow_tf32 = bool(benchmark_config["tf32_enabled"])
    torch.backends.cudnn.allow_tf32 = bool(benchmark_config["tf32_enabled"])
    workers_used = min(int(benchmark_config["workers"]), device_count)
    device_indices = list(range(workers_used))
    model_path = read_sentence_model_path()
    expected_hidden = read_embed_dim()
    phase = "local_model"
    if not Path(model_path).is_dir():
        raise FileNotFoundError(f"local BGE model path does not exist: {{model_path}}")
    sample_text = (
        "ODCR preprocess B profile text for local BGE embedding benchmark. "
        "It mixes content evidence, review style, rating context, and domain semantics. "
    ) * 4
    batch = [sample_text + f" sample {{idx}}" for idx in range(int(benchmark_config["embed_batch_size"]))]
    autocast_enabled = bool(benchmark_config["bf16_enabled"] and torch.cuda.is_bf16_supported())
    workers_state = []
    load_started = time.monotonic()
    for worker_id, device_idx in enumerate(device_indices):
        phase = f"tokenizer_load_worker_{{worker_id}}"
        tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
        phase = f"model_load_worker_{{worker_id}}"
        device = torch.device(f"cuda:{{device_idx}}")
        with torch.cuda.device(device):
            model = AutoModel.from_pretrained(model_path, local_files_only=True)
            model.to(device).eval()
            actual_hidden = int(getattr(model.config, "hidden_size", 0))
            if actual_hidden != expected_hidden:
                raise ValueError(f"BGE hidden_size={{actual_hidden}} does not match expected dim {{expected_hidden}}")
        workers_state.append({{"worker_id": worker_id, "device_idx": device_idx, "device": device, "tokenizer": tokenizer, "model": model}})
    if torch.cuda.is_available():
        for item in workers_state:
            torch.cuda.synchronize(item["device"])
    load_seconds = time.monotonic() - load_started

    def encode_once(item, *, measured):
        device = item["device"]
        tokenizer = item["tokenizer"]
        model = item["model"]
        tokenize_started = time.monotonic()
        encoded = tokenizer(batch, padding=True, truncation=True, max_length=512, return_tensors="pt")
        tokenize_s = time.monotonic() - tokenize_started
        encoded = {{key: value.to(device) for key, value in encoded.items()}}
        torch.cuda.synchronize(device)
        forward_started = time.monotonic()
        with torch.inference_mode():
            with torch.autocast(device_type="cuda", dtype=torch.bfloat16, enabled=autocast_enabled):
                outputs = model(**encoded)
                pooled = outputs.last_hidden_state[:, 0, :].detach().to(torch.float32)
        torch.cuda.synchronize(device)
        forward_s = time.monotonic() - forward_started
        shape = [int(pooled.shape[0]), int(pooled.shape[1])]
        if measured:
            return {{"worker_id": item["worker_id"], "device_idx": item["device_idx"], "tokenize_s": tokenize_s, "forward_s": forward_s, "shape": shape}}
        return {{"worker_id": item["worker_id"], "device_idx": item["device_idx"], "tokenize_s": tokenize_s, "forward_s": forward_s, "shape": shape}}

    def run_parallel(*, measured):
        results = []
        errors = []
        lock = threading.Lock()
        def worker(item):
            try:
                result = encode_once(item, measured=measured)
                with lock:
                    results.append(result)
            except Exception as exc:
                with lock:
                    errors.append({{"worker_id": item["worker_id"], "device_idx": item["device_idx"], "error": repr(exc)}})
        threads = [threading.Thread(target=worker, args=(item,)) for item in workers_state]
        for thread in threads:
            thread.start()
        for thread in threads:
            thread.join()
        if errors:
            raise RuntimeError("worker failed: " + repr(errors))
        return sorted(results, key=lambda item: int(item["worker_id"]))

    emit("micro_benchmark_warmup_batches", 1)
    phase = "forward"
    warmup_results = run_parallel(measured=False)
    for item in workers_state:
        torch.cuda.synchronize(item["device"])
        torch.cuda.reset_peak_memory_stats(item["device"])
    emit("micro_benchmark_measured_batches", 1)
    t0 = time.monotonic()
    measured_results = run_parallel(measured=True)
    for item in workers_state:
        torch.cuda.synchronize(item["device"])
    latency = time.monotonic() - t0
    total_samples = int(len(batch) * workers_used)
    samples_per_sec = total_samples / latency if latency > 0 else 0.0
    memory_by_device = []
    for item in workers_state:
        with torch.cuda.device(item["device"]):
            memory_by_device.append({{"device_idx": item["device_idx"], "max_memory_allocated": int(torch.cuda.max_memory_allocated(item["device"]))}})
    memory = max((int(item["max_memory_allocated"]) for item in memory_by_device), default=0)
    tokenize_s = max((float(item["tokenize_s"]) for item in measured_results), default=0.0)
    forward_s = max((float(item["forward_s"]) for item in measured_results), default=0.0)
    emit("latency_seconds", round(latency, 6))
    emit("samples_per_sec", round(samples_per_sec, 3))
    emit("batch_size", int(benchmark_config["embed_batch_size"]))
    emit("workers_used", workers_used)
    emit("total_samples", total_samples)
    emit("tokenize_seconds", round(tokenize_s, 6))
    emit("forward_seconds", round(forward_s, 6))
    emit("gpu_max_memory_allocated", memory)
    metrics = {{
        "kind": {benchmark_kind!r},
        "parameters": benchmark_config,
        "warmup_batches": 1,
        "measured_batches": 1,
        "load_seconds": load_seconds,
        "latency_seconds": latency,
        "samples_per_sec": samples_per_sec,
        "batch_size": int(benchmark_config["embed_batch_size"]),
        "total_samples": total_samples,
        "workers_requested": int(benchmark_config["workers"]),
        "workers_used": workers_used,
        "device_count": device_count,
        "device_names": device_names,
        "tokenize_s": tokenize_s,
        "forward_s": forward_s,
        "worker_results": measured_results,
        "warmup_results": warmup_results,
        "gpu_max_memory_allocated": memory,
        "max_vram_gb": memory / (1024 ** 3),
        "gpu_memory_by_device": memory_by_device,
        "autocast_bf16": autocast_enabled,
        "tf32_enabled": bool(benchmark_config["tf32_enabled"]),
        "model_path": model_path,
    }}
    emit("ODCR_BRIDGE_END_" + RUN_ID)
    exit_code = finish(True, 0, {spec.stop_reason_success!r}, metrics, True)
except Exception as exc:
    lowered = repr(exc).lower()
    if "out of memory" in lowered:
        stop_reason = "oom"
    elif phase == "dependency_import":
        stop_reason = "dependency_import_error"
    elif phase == "cuda_check":
        stop_reason = "cuda_unavailable"
    elif "tokenizer_load" in phase:
        stop_reason = "tokenizer_load_failed"
    elif "model_load" in phase:
        stop_reason = "model_load_failed"
    elif phase == "forward":
        stop_reason = "forward_failed"
    else:
        stop_reason = "script_exit_nonzero"
    emit("bridge_error", repr(exc))
    emit(traceback.format_exc())
    emit("ODCR_BRIDGE_END_" + RUN_ID)
    exit_code = finish(False, 1, stop_reason, {{"error": repr(exc), "failure_class": stop_reason, "phase": phase, "parameters": benchmark_config}}, False)
finally:
    LOG.close()
sys.exit(exit_code)
"""
    return _script_header(paths) + f'"$PYTHON" - <<\'PY\'\n{body}\nPY\n'


def build_script(
    options: BridgeOptions,
    run_id: str,
    paths: GeneratedPaths,
    timeouts: ResolvedTimeouts,
    target: PaneCandidate,
) -> str:
    if options.mode == "marker-probe":
        return build_marker_probe_script(run_id, paths, timeouts, target)
    if options.mode == "cuda-probe":
        return build_cuda_probe_script(run_id, paths, timeouts, target)
    if options.mode == "bge-smoke":
        return build_bge_smoke_script(run_id, paths, timeouts, target)
    if options.mode == "preprocess-dryrun":
        if not options.stage:
            raise BridgeError("preprocess-dryrun requires --stage b or --stage c", stop_reason="forbidden_mode")
        return build_preprocess_dryrun_script(run_id, paths, timeouts, target, options.stage)
    if options.mode == "micro-benchmark":
        return build_micro_benchmark_script(
            run_id,
            paths,
            timeouts,
            target,
            options.benchmark_kind or "bge-single-batch",
            embed_batch_size=options.embed_batch_size,
            read_chunk_rows=options.read_chunk_rows,
            group_shard_size=options.group_shard_size,
            workers=options.workers,
            bf16_enabled=options.bf16_enabled,
            tf32_enabled=options.tf32_enabled,
            grouped_text_cache_enabled=options.grouped_text_cache_enabled,
        )
    raise BridgeError(f"unsupported script mode: {options.mode}", stop_reason="forbidden_mode")


def collect_run(run_id: str) -> dict[str, Any]:
    paths = make_generated_paths(run_id)
    log_exists = paths.log.is_file()
    status_exists = paths.status.is_file()
    summary_exists = paths.summary.is_file()
    report_exists = paths.report.is_file()
    log_text = paths.log.read_text(encoding="utf-8") if log_exists else ""
    end_marker = f"ODCR_BRIDGE_END_{run_id}" in log_text
    status_data: dict[str, Any] = {}
    if status_exists:
        try:
            status_data = _read_json(paths.status)
        except json.JSONDecodeError:
            status_data = {}
    complete = bool(status_data and end_marker)
    result = {
        "schema_version": BRIDGE_STATUS_SCHEMA,
        "run_id": run_id,
        "kind": "collect",
        "success": bool(complete and status_data.get("success", False)),
        "exit_code": 0 if complete else 1,
        "elapsed_s": 0.0,
        "startup_timeout_s": MODE_SPECS["collect"].startup_timeout_s,
        "first_result_timeout_s": MODE_SPECS["collect"].first_result_timeout_s,
        "hard_timeout_s": MODE_SPECS["collect"].auto_timeout_s,
        "first_result_seen": bool(complete),
        "success_condition": MODE_SPECS["collect"].success_condition,
        "stop_reason": "collected" if complete else "incomplete",
        "metrics": {
            "log_exists": log_exists,
            "status_exists": status_exists,
            "summary_exists": summary_exists,
            "report_exists": report_exists,
            "end_marker_seen": end_marker,
            "source_status": status_data,
        },
        "paths": paths.to_dict(),
    }
    return result


def _add_common_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--dry-run", action="store_true", help="Plan target/script only; do not send keys.")
    parser.add_argument("--timeout", default="auto", help="auto or explicit seconds; capped by mode safety limits.")
    parser.add_argument("--socket", help="Explicit tmux socket path.")
    parser.add_argument("--target", help="Explicit tmux target such as odcr:0.0 or %%0.")
    parser.add_argument("--run-id", help="Optional run id; defaults to bridge_YYYYMMDD_HHMMSS_kind.")
    parser.add_argument("--no-send", action="store_true", help="Generate script/status/report without send-keys.")
    parser.add_argument("--strict", action="store_true", help="Fail fast if target discovery is not unique.")
    parser.add_argument(
        "--send-method",
        choices=SEND_METHODS,
        default=DEFAULT_SEND_METHOD,
        help="Controlled tmux transport method for generated whitelist commands.",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Controlled ODCR tmux GPU bridge.")
    sub = parser.add_subparsers(dest="mode", required=True)

    for mode in ("discover", "validate-only", "unlock-pane", "marker-probe", "cuda-probe", "bge-smoke"):
        _add_common_args(sub.add_parser(mode))

    preprocess = sub.add_parser("preprocess-dryrun")
    _add_common_args(preprocess)
    preprocess.add_argument("--stage", choices=("b", "c"), required=True)

    micro = sub.add_parser("micro-benchmark")
    _add_common_args(micro)
    micro.add_argument("--kind", choices=("bge-single-batch",), default="bge-single-batch")
    micro.add_argument("--embed-batch-size", type=int, default=512)
    micro.add_argument("--read-chunk-rows", type=int, default=100_000)
    micro.add_argument("--group-shard-size", type=int, default=4_096)
    micro.add_argument("--workers", type=int, default=2)
    micro.add_argument("--bf16", action="store_true", default=True, dest="bf16_enabled")
    micro.add_argument("--no-bf16", action="store_false", dest="bf16_enabled")
    micro.add_argument("--tf32", action="store_true", default=True, dest="tf32_enabled")
    micro.add_argument("--no-tf32", action="store_false", dest="tf32_enabled")
    micro.add_argument("--grouped-text-cache", action="store_true", default=True, dest="grouped_text_cache_enabled")
    micro.add_argument("--no-grouped-text-cache", action="store_false", dest="grouped_text_cache_enabled")

    collect = sub.add_parser("collect")
    collect.add_argument("--run-id", required=True)
    collect.add_argument("--timeout", default="auto", help=argparse.SUPPRESS)
    collect.add_argument("--dry-run", action="store_true", help=argparse.SUPPRESS)
    collect.add_argument("--no-send", action="store_true", help=argparse.SUPPRESS)
    collect.add_argument("--strict", action="store_true", help=argparse.SUPPRESS)
    collect.add_argument("--socket", help=argparse.SUPPRESS)
    collect.add_argument("--target", help=argparse.SUPPRESS)
    collect.add_argument("--send-method", choices=SEND_METHODS, default=DEFAULT_SEND_METHOD, help=argparse.SUPPRESS)
    return parser


def options_from_args(args: argparse.Namespace) -> BridgeOptions:
    return BridgeOptions(
        mode=args.mode,
        stage=getattr(args, "stage", None),
        benchmark_kind=getattr(args, "kind", None),
        embed_batch_size=int(getattr(args, "embed_batch_size", 512)),
        read_chunk_rows=int(getattr(args, "read_chunk_rows", 100_000)),
        group_shard_size=int(getattr(args, "group_shard_size", 4_096)),
        workers=int(getattr(args, "workers", 2)),
        bf16_enabled=bool(getattr(args, "bf16_enabled", True)),
        tf32_enabled=bool(getattr(args, "tf32_enabled", True)),
        grouped_text_cache_enabled=bool(getattr(args, "grouped_text_cache_enabled", True)),
        timeout=getattr(args, "timeout", "auto"),
        dry_run=bool(getattr(args, "dry_run", False)),
        no_send=bool(getattr(args, "no_send", False)),
        strict=bool(getattr(args, "strict", False)),
        socket=getattr(args, "socket", None),
        target=getattr(args, "target", None),
        run_id=getattr(args, "run_id", None),
        send_method=getattr(args, "send_method", DEFAULT_SEND_METHOD),
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    bridge = TmuxGpuBridge()
    try:
        result = bridge.run_mode(options_from_args(args))
    except BridgeError as exc:
        payload = {
            "schema_version": BRIDGE_STATUS_SCHEMA,
            "success": False,
            "exit_code": 1,
            "stop_reason": exc.stop_reason,
            "error": str(exc),
            "details": exc.details,
        }
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 1
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0 if result.get("success") else 1


if __name__ == "__main__":
    raise SystemExit(main())
